[variables]
NIXPACKS_NO_DJANGO_COLLECTSTATIC = "1"

[phases.build]
cmds = ["echo 'Custom build phase - nixpacks.toml detected'"]

[phases.start]
cmd = "python manage.py migrate && python manage.py test_railway_import && python manage.py explore_csv_data && python manage.py import_comprehensive_journals && python manage.py import_dental_papers_bulk && python manage.py collectstatic --noinput && gunicorn ost_web.wsgi --log-file -" 