[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "never"

# Post-deployment commands
[deploy.healthcheckPath]
path = "/"

# Environment-specific settings
[environments.production]
variables = {}

# Optional: Run migrations on deploy
[environments.production.deploy]
checkPath = "/" 