# Generated by Django 5.2.4 on 2025-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="broad_subject_term",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="NLM broad subject classification for this paper's journal",
                max_length=200,
                null=True,
            ),
        ),
    ]
