# Generated by Django 5.2.4 on 2025-07-22 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="broad_subject_category",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Primary broad subject category from NLM",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="has_pdf",
            field=models.BooleanField(default=False, help_text="PDF available"),
        ),
        migrations.AddField(
            model_name="paper",
            name="in_epmc",
            field=models.BooleanField(
                default=False, help_text="Available in Europe PMC"
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="in_pmc",
            field=models.BooleanField(default=False, help_text="Available in PMC"),
        ),
        migrations.AddField(
            model_name="paper",
            name="is_open_access",
            field=models.BooleanField(
                default=False, help_text="Open access availability"
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="issue",
            field=models.CharField(
                blank=True, help_text="Journal issue number", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="journal_volume",
            field=models.CharField(
                blank=True, help_text="Journal volume", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="page_info",
            field=models.CharField(
                blank=True, help_text="Page information", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="pub_type",
            field=models.CharField(
                blank=True,
                help_text="Publication type from Europe PMC",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="transparency_score",
            field=models.IntegerField(
                default=0,
                help_text="Total transparency score (0-8)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
    ]
