# Generated by Django 5.2.4 on 2025-07-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_add_transparency_averages_to_research_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="assessment_tool",
            field=models.CharField(
                db_index=True,
                default="rtransparent",
                help_text="Tool used for transparency assessment (e.g., rtransparent, manual)",
                max_length=50,
            ),
        ),
    ]
