# Generated by Django 5.2.4 on 2025-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_add_assessment_tool_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paper",
            options={
                "ordering": ["-pub_year", "title"],
                "verbose_name": "Research Paper",
                "verbose_name_plural": "Research Papers",
            },
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(fields=["source"], name="tracker_pap_source_0ba57a_idx"),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["assessment_tool"], name="tracker_pap_assessm_531db7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["broad_subject_term"], name="tracker_pap_broad_s_e0a564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["pub_type"], name="tracker_pap_pub_typ_1b4874_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["journal_id"], name="tracker_pap_journal_3074b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["journal_issn"], name="tracker_pap_journal_7445f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(fields=["title"], name="tracker_pap_title_8b7f53_idx"),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["author_string"], name="tracker_pap_author__7a6515_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["created_at"], name="tracker_pap_created_267ba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["first_publication_date"], name="tracker_pap_first_p_314727_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["processing_date"], name="tracker_pap_process_a160e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["pub_year", "transparency_score"],
                name="tracker_pap_pub_yea_ed6cf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["journal_id", "pub_year"], name="tracker_pap_journal_d88b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["broad_subject_term", "transparency_score"],
                name="tracker_pap_broad_s_8dfd5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["source", "assessment_tool"],
                name="tracker_pap_source_0d5209_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["transparency_processed", "assessment_tool"],
                name="tracker_pap_transpa_8dac7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["pub_year", "is_open_data", "is_open_code"],
                name="tracker_pap_pub_yea_deea39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["journal_id", "transparency_score", "pub_year"],
                name="tracker_pap_journal_287268_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="paper",
            table="tracker_paper",
        ),
    ]
